### ISSUE TITLE
Day 1 Activity 1, 404 dead link. 

### ISSUE THREAD

**Issue by nbreznau** [rstudio-conf-2022/get-started-quarto#1]
Doesn't resolve when clicking for me.

**Comment by jthomasmock** [comment]
I'm sorry, I'm not sure what activity you're looking for?

The workshop materials are available via a git clone of: `https://github.com/jthomasmock/quarto-workshop.git`

**Comment by nbreznau** [comment]
I can access the materials, thanks. 

I wanted to simply point out that the 'clickable' links in the Readme.Rmd don't work in the daily Schedule table. Thought you might like to know.

**Comment by jthomasmock** [comment]
Gotcha! The readme was a QMD that GitHub isn't acknowledging all of the material. I've simplified the readme so that it points to the workshop website/slides and then the other repo with hands-on-keyboard workshop material.
